name: Linter

on:
  push:

env:
  GO_VERSION: 1.15

jobs:
  linter:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
      - name: Checking out repository
        uses: actions/checkout@v3

      - name: Setting up Go environment
        uses: actions/setup-go@v3
        with:
          go-version: '^${{ env.GO_VERSION }}'
          cache: true
          cache-dependency-path: go.sum

      - name: Download gomod dependencies
        run: go mod download -x

      - name: Run linters
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: -v -c .golangci.yml --timeout 10m
          # skip-cache: true
          # skip-pkg-cache: true
          # skip-build-cache: true